import type { BrandConfig } from "@/types/brand";

export const BRAND: BrandConfig = {
  businessName: "Kinathiyil Gold & Diamonds",
  tagline: "Timeless Gold, Diamond & Silver Jewellery in Perinthalmanna",
  description: "Kinathiyil Gold & Diamonds is Perinthalmanna’s trusted destination for gold, diamond and silver jewellery. Nestled in the heart of Shanti Nagar, Perinthalmanna, we bring you an exquisite collection of handcrafted gold ornaments, dazzling diamond pieces, and elegant silver jewellery — each crafted with passion and precision. Visit us and experience jewellery that tells your story.",
  logo: "/icons/logo.svg",
  favicon: "/favicon.ico",
  heroVideo: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4",
  storyVideos: [
    {
      quote: "ലാളിത്യത്തിലെ പൂർണ്ണത.",
      description: "അണിയാൻ തീരെ ഭാരമില്ലാത്ത, എന്നാൽ കണ്ണഞ്ചിപ്പിക്കുന്ന ഡിസൈനുകൾ. നിങ്ങളുടെ ഓരോ സാധാരണ ദിവസത്തെയും മനോഹരമാക്കാൻ ഇവ മതിയാകും.",
      video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4",
      segments: { startAt: 0, loopEnd: 8 },
    },
    {
      quote: "കൈകളിൽ വിരിയുന്ന വിസ്മയം.",
      description: "ഓരോ ആഭരണവും ഓരോ കലാരൂപമാണ്. അതിസൂക്ഷ്മമായി, തികഞ്ഞ പൂർണ്ണതയോടെ രൂപപ്പെടുത്തിയെടുത്തവ. നിങ്ങളുടെ സ്വപ്നങ്ങൾക്ക് സ്വർണ്ണത്തിൽ ജീവൻ വയ്ക്കുമ്പോൾ.",
      video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4",
      segments: { startAt: 32, loopEnd: 40 },
    },
    {
      quote: "പെരിന്തൽമണ്ണയുടെ ഹൃദയത്തിൽ നിന്ന്.",
      description: "ഈ നാടിന്റെ പൈതൃകവും പുതുമയും ഒത്തുചേരുന്ന ആഭരണങ്ങൾ. തലമുറകളായി നിങ്ങൾ നൽകുന്ന വിശ്വാസത്തിന് സ്വർണ്ണത്തേക്കാൾ തിളക്കമുണ്ട്.",
      video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4",
      segments: { startAt: 16, loopEnd: 24 },
    },
  ],
  storeImages: [
    "/images/store1.webp",
    "/images/store2.webp",
    "/images/store3.webp",
    "/images/store4.webp",
  ],
  address: "Kinathiyil Building, Mannarkkad Rd Junction, Shanti Nagar, Perinthalmanna, Kerala 679322",
  city: "Perinthalmanna",
  state: "Kerala",
  pincode: "679322",
  phone: "+919846049843",
  whatsapp: "919846049843",
  email: "",
  mapsLink: "https://share.google/mbbUtzcdRNssuUJYY",
  openingHours: "Mon–Sat: 9:30 AM – 8:00 PM · Sunday: 10:00 AM – 7:00 PM",
  instagram: "https://www.instagram.com/kinathiyil_gold_and_diamonds",
  facebook: "https://www.facebook.com/kinathiyilgoldanddiamonds",
  seo: {
    title: "Kinathiyil Gold & Diamonds | Jewellery in Perinthalmanna",
    description: "Kinathiyil Gold & Diamonds - gold, diamond and silver jewellery in Perinthalmanna, Kerala. Explore our stunning collections of traditional and modern designs.",
    keywords: ["Kinathiyil Gold & Diamonds", "jewellery Perinthalmanna", "gold jewellery Perinthalmanna", "diamond jewellery Perinthalmanna", "silver jewellery Perinthalmanna"],
    canonical: "https://kinathiyil-gold-diamonds-shanti-nag-beta.vercel.app",
    ogImage: "https://kinathiyil-gold-diamonds-shanti-nag-beta.vercel.app/images/store1.webp",
  },
  faq: [],
  whatsappMessage: "Hello Kinathiyil Gold & Diamonds, I’d like to know more about your jewellery collections.",
};
